services:
  nginx:
    network_mode: host
  molgenis:
    network_mode: host
  postgresql:
    network_mode: host
  elasticsearch:
    network_mode: host
  minio:
    network_mode: host

version: "3.8"
